name: Scheduled Purge

on:
  schedule:
    - cron: "0 3 * * *" # run daily at 3am UTC
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Call purge endpoint
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"channel_id":"838466787921362964"}' \
            https://your-vercel-app.vercel.app/api/purge
